---

- hosts: myserver
  gather_facts: True

  become: true
  become_method: sudo

  tasks:

   - name: updating password for root
     user: name=root update_password=always password=$6$16_test$BSMVwGZj/nlSTF6Z0M7nwS/3eO140BedB2yJltosdfdsfdsfcxjcYN7ojbuKNGOkxczxcVtiGXIiU1RMYs.
     

