#WORK IN PROGRESS
#IDEALLY THIS PLAYBOOK WILL:
# -create GCE instance
# -install steamcmd
# -install LinuxGSM
# -install arma3server
# -config arma3server
# -power off instance
# -upgrade instance type


#Basic provisioning example.  Create a single Debian 8 instance in the
# us-central1-a Zone of the n1-standard-1 machine type.
# Create multiple instances by specifying multiple names, separated by
# commas in the instance_names field
# (e.g. my-test-instance1,my-test-instance2)
- name: Create ArmA 3 Server
  hosts: localhost
  vars:
    service_account_email: "ansible-svc@gameservers-255600.iam.gserviceaccount.com"
    credentials_file: "~/serviceaccounts/ansible.json"
    project_id: "gameservers"
  tasks:
    - name: create instance
      gce:
        instance_names: arma3server
        zone: us-central1-a
        machine_type: n1-standard-1
        image: debian-8
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
      register: gcea

#- name: Save host data
#    add_host:
#    hostname: "{{ item.public_ip }}"
#    groupname: gce_instances_ips
#  with_items: "{{ gce.instance_data }}"

#- name: Wait for SSH for instances
#  wait_for:
#    delay: 1
#    host: "{{ item.public_ip }}"
#    port: 22
#    state: started
#    timeout: 30
#  with_items: "{{ gce.instance_data }}"

#- name: Configure Hosts
#  hosts: gce_instances_ips
#  become: yes
#  become_method: sudo
#  roles:
#    - my-role-one
#    - my-role-two
#  tags:
#    - config
