---

- name: add dpkg architecture
  command: dpkg --add-architecture i386
  become: yes

- name: install requisite packages
  apt:
    pkg:
    - mailutils
    - postfix
    - curl
    - wget
    - file
    - tar
    - bzip2
    - gzip
    - unzip
    - bsdmainutils
    - python
    - util-linux
    - ca-certificates
    - binutils
    - bc
    - jq
    - tmux
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
